export { retrieve, prune, classifyNode, deduplicate, rankByQuery, type RetrievalRelevance, type RetrievalFocus } from "./retrieval-engine.js"
export { serialize } from "./serializer.js"
export { naiveRag, compare, type NaiveRagResult, type ComparisonReport } from "./naive-rag.js"
export { fuseWithRuntime, type FusedRetrievalResult } from "./fused-retrieval.js"
export { buildDependencyIndex, queryDependents, indexStats, type DependencyIndex, type DependencyHit } from "./dependency-index.js"
export { captureBaseline, verifyBaseline, saveBaseline, loadBaseline, CRITICAL_NODE_TYPES } from "./retrieval-baseline.js"
export type { RetrievalBaseline, RetrievalBaselineEntry, BaselineDrift, BaselineVerifyResult } from "./retrieval-baseline.js"
export { captureTopologyBaseline, verifyTopologyBaseline, saveTopologyBaseline, loadTopologyBaseline } from "./topology-baseline.js"
export type { TopologyBaseline, TopologyBaselineEntry, TopologyDrift, TopologyVerifyResult } from "./topology-baseline.js"
